# This is a basic workflow to help you get started with Actions

name: mkdocs-mike-deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  docs_deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
        

      - name: install-deps
        run: |
          apk update && apk add bash curl jq gcc libc-dev libffi-dev zlib-dev jpeg-dev g++
          pip install --upgrade pip
          pip install mkdocs-material mkdocs-with-pdf mike

      # Inject version and document revision information into docs/ source      
      # Build and deploy docs site and pdf
      - name: docs-deploy
        run: |
          VER=$( CI/inject_version )
          MAJMIN=$(echo ${VER} | grep -o '[0-9]\+\.[0-9]\+')
          git config user.name "GitHub Actions CI Publisher"
          git config user.email "DyalogGithubActions@github.com"
          git fetch origin gh-pages --depth=1
          git checkout gh-pages
          git pull origin gh-pages
          git checkout master
          mike deploy ${MAJMIN}
          mike set-default ${MAJMIN}
          mike alias --update-aliases --push ${MAJMIN} latest
 
